# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=300)),
                ('emailName', models.CharField(max_length=300)),
                ('passName', models.CharField(max_length=300)),
            ],
        ),
    ]
