# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactlist',
            name='emailName',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='passName',
        ),
        migrations.RemoveField(
            model_name='contactlist',
            name='userName',
        ),
        migrations.AddField(
            model_name='contactlist',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='name',
            field=models.CharField(default='dummmy', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactlist',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
